[project]
version = "2025.02.03"
name = "tekken-project"
requires-python = ">= 3.13"
dependencies = [
  "django>=5.1.5",
]
description = "Python tekken project"
readme = "README.md"
authors = [
  {name = "Bondoux Lenny"},
]
maintainers = [
  {name = "Bondoux Lenny"},
]